# Generated by Django 6.0 on 2026-01-02 23:24

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('slug', models.SlugField(max_length=25, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
                'db_table': 'pages_types',
                'indexes': [models.Index(fields=['slug'], name='pages_types_slug_22f3f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('path', models.CharField(editable=False, max_length=255, unique=True)),
                ('route_name', models.CharField(max_length=255, unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Is this page enabled?', verbose_name='Enabled')),
                ('is_home', models.BooleanField(default=False, help_text='The home page is the default landing page for the website.', verbose_name='Home Page')),
                ('is_visible', models.BooleanField(default=True, help_text='Disable to hide this page from page based navigation <strong>structure</strong>.', verbose_name='Visible')),
                ('is_exact', models.BooleanField(default=False, help_text='Disable to allow custom parameters following the URI for this page.', verbose_name='Exact URI')),
                ('order', models.IntegerField(default=0, editable=False, verbose_name='Order')),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta Keywords')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.page')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.type')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'db_table': 'pages_pages',
                'indexes': [models.Index(fields=['parent', 'order'], name='pages_pages_parent__99f453_idx'), models.Index(fields=['slug'], name='pages_pages_slug_b61cfa_idx')],
            },
        ),
    ]
